### ISSUE TITLE
Abgespielte Beschreibung != angezeigte Textur

### ISSUE THREAD

**Issue by TheL1ne** [holycrab13/TactileGame#14]
Wenn ich 2 Texturen auf dem gleichen Feld platziere wird die Textur angezeigt, die weiter unten im Level-XML steht. Allerdings wird die beschreibung des weiter oben stehenden Elemts abgespielt. Es wäre gut wenn die Beschreibung des sichtbaren Elements abgespielt wird.

**Comment by TheL1ne** [comment]
gilt zum Beispiel bei dem Auto der Müllers

**Comment by holycrab13** [comment]
"prio" tag auf WorldObject auf eine zahl > 0 setzen, Interaktions-target mit höchster Priorität wird für Interaktion verwendet. Beispiel auf dem Auto der Müllers.
Default Priority-Wert ist 0.
