### ISSUE TITLE
Texturflackern extrem

### ISSUE THREAD

**Issue by TheL1ne** [holycrab13/TactileGame#16]
Ich hab meinen Rechner neu gemacht mit Win7 statt WIn10 und das flackern ist extrem schlimm. Manche Sachen werden dadurch niemals sichtbar. eventuel sollten wir nur neuzeichen, wenn sich etwas bewegt.

**Comment by TheL1ne** [comment]
fixed: https://github.com/holycrab13/TactileGame/pull/20

**Comment by holycrab13** [comment]
Wie hast du das gefixt? Bei dir oder im code?

**Comment by TheL1ne** [comment]
@holycrab13 hab ich in meinem branch gefixt. du kannst dir den commit anschauen: https://github.com/holycrab13/TactileGame/pull/20/commits/24ce342ef9c445b724c63358509a5698f2aeb6a4
