### ISSUE TITLE
Tastkonsistenz

### ISSUE THREAD

**Issue by TheL1ne** [holycrab13/TactileGame#23]
Texturen mit durchgezogenem Rand blockieren
Texturen mit "durchlässigem" Rand sind durchgänglich

**Comment by holycrab13** [comment]
Also der Editor macht jetzt glaub ich das Richtige, das laden mit Village und Pub hat jedenfalls funktioniert, sodass die rotations gepasst haben, hab das XML gespeichert und im Tactile geladen, lief soweit auch alles rund!
Sag bescheid wenn ich noch irgendwo Blödsinn gemacht hab! 😊

Gesendet von Windows Mail

Von: Benjamin Riedel<mailto:notifications@github.com>
Gesendet: ‎Sonntag‎, ‎19‎. ‎November‎ ‎2017 ‎18‎:‎48
An: holycrab13/TactileGame<mailto:TactileGame@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>


Texturen mit durchgezogenem Rand blockieren
Texturen mit "durchlässigem" Rand sind durchgänglich
