### ISSUE TITLE
Kollisionshinweis

### ISSUE THREAD

**Issue by TheL1ne** [holycrab13/TactileGame#36]
Falls man mit Gegenständen kollidiert sollte ein hinweis abgespielt werden (evtl. erst bei mehrmaligem Kollidieren an gleicher stelle?)

**Comment by holycrab13** [comment]
Sound wird abgespielt, wenn man mehrfach gegen eine Wand rennt und auch die Orientierung des Characters nicht ändert.
Check mal den CharacterController.cs, dass das auch bei dir mit dem Absoluten Pfad hinhaut. (sollte eigentlich funktionieren) Framework ist hier blöd: Sound-Files sind nur lesbar, wenn ein absoluter Pfad angegeben wird, wäre gut, dass als Feedback an den Jens zu geben.
