### ISSUE TITLE
Fortsetzen von Interaktion mit allen Tasten

### ISSUE THREAD

**Issue by TheL1ne** [holycrab13/TactileGame#38]
Dialoge und Erklärungen sollten bei dem Druck einer beliebeigen Taste weiter gehen bzw. sich beenden.

**Comment by holycrab13** [comment]
Ist kompliziert, bei einfachem Drücken werden oft Events aus Versehen übersprungen.
"Letztes Event" ist nicht so einfach festzustellen..

**Comment by TheL1ne** [comment]
geht es nicht einfach den nächsten Teil eines Events zu triggern, wie es
jetzt bei Eingabe ist, auf alle tasten auszuweiten? dann kommt schließlich
eine ansage, wenn man eine Taste drückt. ich würde das gerne ausprobieren.

**Comment by holycrab13** [comment]
Implementiert, verwendet eine extra Map um versehentliches Überspringen zu verhindern! Sollte noch ein bisschen getestet werden!
